spring.application.name=snaplink

#  Settings of the DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# setting logging config
logging.file.name=logs/app.log
logging.file.path=logs